# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distilleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='name',
            field=models.CharField(max_length=255, null=True),
            preserve_default=False,
        ),
    ]
