# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distilleries', '0003_populate_name_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillery',
            name='name',
            field=models.CharField(default='New Distillery', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
