# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 20:22
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import utils.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/lhadjchikh/Documents/cyphon/keys'), upload_to='', validators=[utils.validators.validators.key_file_validator]),
        ),
    ]
