# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasieves', '0003_auto_20170717_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarule',
            name='value',
            field=models.CharField(blank=True, help_text='The value to compare the data against. If using regex, the output of the regex is used for comparison.', max_length=255, null=True),
        ),
    ]
