# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 20:21
from __future__ import unicode_literals

import cyphon.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasieves', '0004_auto_20180309_2021'),
        ('actions', '0002_auto_20170822_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('action', models.ForeignKey(help_text='The Action to perform.', on_delete=django.db.models.deletion.PROTECT, to='actions.Action')),
                ('sieve', models.ForeignKey(blank=True, help_text='The DataSieve used to inspect the data during this step.', null=True, on_delete=django.db.models.deletion.PROTECT, to='datasieves.DataSieve')),
            ],
        ),
    ]
