# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20170320_1223'),
        ('tags', '0002_auto_20170810_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('exact_match', models.BooleanField(default=False, help_text='Add new tags from this field (only available when using exact match).')),
                ('create_tags', models.BooleanField(default=False, help_text='Add new tags from this field (only available when using exact match).')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.Container')),
            ],
            options={
                'ordering': ['container', 'field_name'],
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Tags must be lowercase.', max_length=255, unique=True, validators=[utils.validators.validators.lowercase_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='datatagger',
            unique_together=set([('container', 'field_name')]),
        ),
    ]
